print("tim" == "tie")
print("free" != "freedom")
print("arrow" > "aron")
print("right" >= "left")
print("teeth" < "tee")
print("yellow" <= "fellow")
print("abc" > "")
print("luis" < "angie")
print("angie" > "emilia")
print("Lord of the Rings The Fellowship of the Ring" < "Lord of the Rings The Two Towers")